"use strict";

// Golden-vector tests for src/crypto.js against fixtures/crypto.json
// (generated by RUNNING apps/server/dekobloko_server/crypto.py).

const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");

const crypto = require("../src/crypto.js");

const fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "crypto.json"), "utf8")
);

let pass = 0;
let vectors = 0;
const failures = [];

function check(label, fn) {
  try {
    fn();
    pass += 1;
  } catch (err) {
    failures.push(label + ": " + err.message);
  }
}

// --- scalar conversions ------------------------------------------------------

for (const c of fixture.scalars) {
  const label =
    c.op + "(" +
    (c.args !== undefined ? c.args.join(", ") : c.in_hex + " @" + c.offset) +
    ")";
  check(label, () => {
    if (c.op === "read_i32_be") {
      const out = crypto.read_i32_be(Buffer.from(c.in_hex, "hex"), c.offset);
      assert.strictEqual(out, c.out, "got " + out);
    } else {
      const fn = crypto[c.op];
      assert.strictEqual(typeof fn, "function", "missing export " + c.op);
      const out = fn(...c.args);
      assert.strictEqual(out, c.out, "got " + out);
    }
  });
  vectors += 1;
}

// --- XTEA ---------------------------------------------------------------------

for (const c of fixture.xtea) {
  const keys = c.keys;
  if (c.error !== undefined) {
    check("xtea " + c.name + " raises", () => {
      assert.throws(
        () => crypto.xtea_encrypt_dekobloko(Buffer.from(c.in_hex, "hex"), keys),
        (err) => err.name === "ValueError" && err.message === c.error
      );
    });
  } else {
    check("xtea " + c.name, () => {
      const fn =
        c.dir === "encrypt"
          ? crypto.xtea_encrypt_dekobloko
          : crypto.xtea_decrypt_dekobloko;
      const out = fn(Buffer.from(c.in_hex, "hex"), keys);
      assert.strictEqual(
        Buffer.from(c.out_hex, "hex").equals(out),
        true,
        "got " + out.toString("hex")
      );
    });
  }
  vectors += 1;

  // Alias must behave identically.
  if (c.error === undefined) {
    check("xtea alias " + c.name, () => {
      const alias =
        c.dir === "encrypt" ? crypto.xtea_encrypt : crypto.xtea_decrypt;
      const out = alias(Buffer.from(c.in_hex, "hex"), keys);
      assert.ok(out.equals(Buffer.from(c.out_hex, "hex")), "alias diverged");
    });
  }
}

// Round-trip property over every encrypt vector's plaintext.
check("xtea enc/dec round-trips on all plaintexts", () => {
  for (const c of fixture.xtea) {
    if (c.dir !== "encrypt" || c.error !== undefined) continue;
    const ct = crypto.xtea_encrypt_dekobloko(Buffer.from(c.in_hex, "hex"), c.keys);
    const pt = crypto.xtea_decrypt_dekobloko(ct, c.keys);
    assert.ok(pt.equals(Buffer.from(c.in_hex, "hex")), c.name);
  }
});

// --- ISAAC --------------------------------------------------------------------

for (const c of fixture.isaac) {
  if (c.stream_hex !== undefined) {
    check("isaac stream " + c.name, () => {
      const cipher = new crypto.IsaacCipher(c.seed);
      const got = [];
      for (let i = 0; i < c.stream_hex.length; i++) {
        got.push(cipher.next().toString(16).padStart(8, "0"));
      }
      // Compare in one join so a single mismatch names its index via diff len.
      assert.strictEqual(got.length, c.stream_hex.length, "length");
      for (let i = 0; i < got.length; i++) {
        assert.strictEqual(got[i], c.stream_hex[i], "word " + i);
      }
    });
    vectors += 1;
  }

  if (c.next_byte_hex !== undefined) {
    check("isaac opcode_helpers " + c.name, () => {
      const nb = new crypto.IsaacCipher(c.seed);
      let bytes = "";
      for (let i = 0; i < 12; i++) bytes += nb.next_byte().toString(16).padStart(2, "0");
      assert.strictEqual(bytes, c.next_byte_hex, "next_byte stream");

      const enc = new crypto.IsaacCipher(c.seed);
      const encHex = c.plaintext_ops.map((op) =>
        enc.encrypt_opcode(op).toString(16).padStart(2, "0")
      );
      assert.deepStrictEqual(encHex, c.encrypted_ops_hex, "encrypt_opcode");

      const dec = new crypto.IsaacCipher(c.seed);
      const plain = c.encrypted_ops_hex.map((h) =>
        dec.decrypt_opcode(parseInt(h, 16))
      );
      assert.deepStrictEqual(plain, c.decrypted_ops, "decrypt_opcode");
      assert.deepStrictEqual(plain, c.plaintext_ops, "round-trip");
    });
    vectors += 1;
  }
}

// Constructor edge: seed longer than 256 uses only seed[:256].
check("isaac truncates seeds to 256 words", () => {
  const long = Array.from({ length: 300 }, (_, i) => (i * 2654435761) >>> 0);
  const a = new crypto.IsaacCipher(long);
  const b = new crypto.IsaacCipher(long.slice(0, 256));
  for (let i = 0; i < 8; i++) assert.strictEqual(a.next(), b.next(), "word " + i);
});

// --- RSA ----------------------------------------------------------------------

for (const c of fixture.rsa) {
  check("rsa " + c.name, () => {
    const key = new crypto.RsaPrivateKey({
      n: BigInt(c.key.n),
      d: BigInt(c.key.d),
      e: BigInt(c.key.e),
    });
    const out = key.decrypt_block(Buffer.from(c.cipher_hex, "hex"));
    assert.strictEqual(
      out.toString("hex"),
      c.plain_hex,
      "got " + out.toString("hex")
    );
  });
  vectors += 1;
}

// from_json / load against the deployment schema (decimal strings / ints).
check("rsa from_json + load + default e", () => {
  const small = fixture.rsa.find((c) => c.name === "small_textbook_msg72");
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dk-rsa-"));

  const withE = path.join(dir, "with-e.json");
  fs.writeFileSync(
    withE,
    JSON.stringify({ n: small.key.n, d: small.key.d, e: small.key.e })
  );
  const keyA = crypto.RsaPrivateKey.from_json(withE);
  assert.strictEqual(keyA.e, BigInt(small.key.e), "e parsed");
  const loaded = crypto.RsaPrivateKey.load(withE); // monkeypatched alias
  assert.strictEqual(loaded.d, keyA.d, "load == from_json");

  const withoutE = path.join(dir, "without-e.json");
  fs.writeFileSync(withoutE, JSON.stringify({ n: small.key.n, d: small.key.d }));
  const keyB = crypto.RsaPrivateKey.from_json(withoutE);
  assert.strictEqual(keyB.e, 65537n, "default e");

  // Same decryption as the golden case through the file-loaded key.
  const out = keyA.decrypt_block(Buffer.from(small.cipher_hex, "hex"));
  assert.strictEqual(out.toString("hex"), small.plain_hex, "file-loaded decrypt");

  // frozen dataclass semantics.
  assert.throws(() => {
    "use strict";
    keyA.n = 1n;
  }, TypeError);

  fs.rmSync(dir, { recursive: true, force: true });
});

// zero-ciphertext contract lives outside the fixture too: b"\x00"*k -> b"\x00".
check("rsa zero ciphertext yields single zero byte", () => {
  const c = fixture.rsa.find((v) => v.name === "zero_cipher");
  const out = new crypto.RsaPrivateKey({
    n: BigInt(c.key.n),
    d: BigInt(c.key.d),
  }).decrypt_block(Buffer.alloc(c.cipher_hex.length / 2));
  assert.strictEqual(out.length, 1);
  assert.strictEqual(out[0], 0);
});

// ------------------------------------------------------------------------------

console.log(
  "crypto: " +
    pass +
    "/" +
    (pass + failures.length) +
    " checks passed (" +
    vectors +
    " fixture vectors)"
);
for (const f of failures) console.log("  FAIL " + f);
process.exit(failures.length === 0 ? 0 : 1);
