"use strict";

// Golden-vector tests for src/login.js against fixtures/login.json
// (generated by RUNNING apps/server/dekobloko_server/login.py via
// test/gen-vectors.py login, against the real deployment RSA key).

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const crypto = require("../src/crypto.js");
const login = require("../src/login.js");

const fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "login.json"), "utf8")
);

let pass = 0;
let vectors = 0;
const failures = [];

function check(label, fn) {
  try {
    fn();
    pass += 1;
  } catch (err) {
    failures.push(label + ": " + err.message);
  }
}

// The real deployment key, embedded as decimal strings (n/d exceed 2**53).
const rsaKey = new crypto.RsaPrivateKey({
  n: fixture.key.n,
  d: fixture.key.d,
  e: fixture.key.e,
});

// --- decode_base37 -------------------------------------------------------------

for (const c of fixture.base37) {
  check("base37(" + c.in + ") -> " + JSON.stringify(c.out), () => {
    const v = BigInt(c.in);
    assert.strictEqual(login.decode_base37(v), c.out);
    // Number and BigInt inputs must agree inside the double-exact envelope.
    if (v <= BigInt(Number.MAX_SAFE_INTEGER) && v >= Number.MIN_SAFE_INTEGER) {
      assert.strictEqual(login.decode_base37(Number(v)), c.out);
    }
  });
  vectors += 1;
}

// --- decode_base38_pair ---------------------------------------------------------

for (const c of fixture.base38) {
  check("base38_pair " + c.in_hex.slice(0, 12) + ".. -> " + JSON.stringify(c.out), () => {
    assert.strictEqual(login.decode_base38_pair(Buffer.from(c.in_hex, "hex")), c.out);
  });
  vectors += 1;
}

// --- PacketReader ----------------------------------------------------------------

for (const c of fixture.reader) {
  check("reader " + c.name, () => {
    const reader = new login.PacketReader(Buffer.from(c.in_hex, "hex"));
    reader.pos = c.pos;
    if (c.error !== undefined) {
      assert.throws(
        () => {
          if (c.op === "read_bytes") reader.read_bytes(c.size);
          else if (c.op === "remaining") reader.remaining();
          else reader[c.op]();
        },
        (err) => err.name === c.error && err.message === c.message
      );
      return;
    }
    let out;
    if (c.op === "read_bytes") out = reader.read_bytes(c.size);
    else if (c.op === "remaining") out = reader.remaining();
    else out = reader[c.op]();
    if (c.out_hex !== undefined) {
      assert.ok(Buffer.isBuffer(out), "expected a Buffer");
      assert.strictEqual(out.toString("hex"), c.out_hex);
    } else {
      assert.deepStrictEqual(out, c.out);
    }
    assert.strictEqual(reader.pos, c.end_pos, "end pos " + reader.pos);
  });
  vectors += 1;
}

// --- parse_login_body -------------------------------------------------------------

function serialize(parsed) {
  return {
    prefix: {
      client_revision: parsed.prefix.client_revision,
      client_detail: String(parsed.prefix.client_detail),
      flags: parsed.prefix.flags,
      client_string: parsed.prefix.client_string,
      extra_token_hex:
        parsed.prefix.extra_token === null
          ? null
          : parsed.prefix.extra_token.toString("hex"),
    },
    rsa_plain_hex: parsed.rsa_plain.toString("hex"),
    xtea_keys: [...parsed.xtea_keys],
    xtea_plain_length: parsed.xtea_plain_length,
    client_seed: [...parsed.client_seed],
    client_seed_signed: [...parsed.client_seed_signed],
    challenge_seed: String(parsed.challenge_seed),
    challenge_matches: parsed.challenge_matches,
    random_uid_hex: parsed.random_uid.toString("hex"),
    credentials: {
      username: parsed.credentials.username,
      password: parsed.credentials.password,
      login_mode: parsed.credentials.login_mode,
      credential_kind: parsed.credentials.credential_kind,
      username_raw: String(parsed.credentials.username_raw),
    },
  };
}

for (const c of fixture.login) {
  check("login " + c.name, () => {
    const body = Buffer.from(c.body_hex, "hex");
    const challenge = BigInt(c.expected_challenge);
    if (c.error !== undefined) {
      assert.throws(
        () => login.parse_login_body(body, rsaKey, challenge),
        (err) => err.name === c.error.type && err.message === c.error.message,
        "expected ValueError: " + c.error.message
      );
      return;
    }
    assert.deepStrictEqual(serialize(login.parse_login_body(body, rsaKey, challenge)), c.result);
  });
  vectors += 1;
}

// --- port-specific contracts --------------------------------------------------------

check("u64 fields stay Number under 2**53 and BigInt beyond", () => {
  // empty_credentials_mode0 carries client_detail=7; long_name case raw > 2**53.
  const small = fixture.login.find((c) => c.name === "empty_credentials_mode0");
  const parsedSmall = login.parse_login_body(
    Buffer.from(small.body_hex, "hex"),
    rsaKey,
    BigInt(small.expected_challenge)
  );
  assert.strictEqual(typeof parsedSmall.prefix.client_detail, "number");
  assert.strictEqual(parsedSmall.credentials.username_raw, 0);

  const big = fixture.login.find((c) => c.name === "long_name_beyond_double53");
  const parsedBig = login.parse_login_body(
    Buffer.from(big.body_hex, "hex"),
    rsaKey,
    BigInt(big.expected_challenge)
  );
  assert.strictEqual(typeof parsedBig.credentials.username_raw, "bigint");
  assert.strictEqual(typeof parsedBig.challenge_seed, "bigint");
  assert.strictEqual(
    parsedBig.credentials.username_raw,
    BigInt(fixture.base37[fixture.base37.length - 1].in)
  );
});

check("challenge comparison masks expected to 64 bits", () => {
  const matchCase = fixture.login.find((c) =>
    c.result && c.result.challenge_matches
  );
  const body = Buffer.from(matchCase.body_hex, "hex");
  const offset = 1n << 64n; // same bits above the mask must still match
  const ok = login.parse_login_body(body, rsaKey, BigInt(matchCase.expected_challenge) + offset);
  assert.strictEqual(ok.challenge_matches, true);
});

check("_parse_credentials honours DEKOBLOKO_DEBUG_LOGIN without altering results", () => {
  const c = fixture.login.find((x) => x.name === "string_base38_mode0_match");
  process.env.DEKOBLOKO_DEBUG_LOGIN = "1";
  try {
    const parsed = login.parse_login_body(
      Buffer.from(c.body_hex, "hex"),
      rsaKey,
      BigInt(c.expected_challenge)
    );
    assert.deepStrictEqual(serialize(parsed), c.result);
  } finally {
    delete process.env.DEKOBLOKO_DEBUG_LOGIN;
  }
});

check("frozen dataclass semantics", () => {
  const c = fixture.login.find((x) => x.result);
  const parsed = login.parse_login_body(
    Buffer.from(c.body_hex, "hex"),
    rsaKey,
    BigInt(c.expected_challenge)
  );
  assert.throws(() => {
    "use strict";
    parsed.credentials.username = "mallory";
  }, TypeError);
  assert.throws(() => {
    "use strict";
    parsed.prefix.flags = 0xff;
  }, TypeError);
});

// -------------------------------------------------------------------------------------

console.log(
  "login: " +
    pass +
    "/" +
    (pass + failures.length) +
    " checks passed (" +
    vectors +
    " fixture vectors)"
);
for (const f of failures) console.log("  FAIL " + f);
process.exit(failures.length === 0 ? 0 : 1);
