"use strict";

// Golden-vector tests for src/packets.js against fixtures/packets.json
// (generated by RUNNING apps/server/dekobloko_server/packets.py via
// test/gen-packets-vectors.py).

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const packets = require("../src/packets.js");

const fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "packets.json"), "utf8")
);

let pass = 0;
let vectors = 0;
const failures = [];

function check(label, fn) {
  try {
    fn();
    pass += 1;
  } catch (err) {
    failures.push(label + ": " + err.message);
  }
}

/** Decode fixture sentinels into JS values (bytes / BigInt / plain). */
function conv(value) {
  if (Array.isArray(value)) return value.map(conv);
  if (value !== null && typeof value === "object") {
    if (value.__hex__ !== undefined) return Buffer.from(value.__hex__, "hex");
    if (value.__bigint__ !== undefined) return BigInt(value.__bigint__);
    const out = {};
    for (const key of Object.keys(value)) out[key] = conv(value[key]);
    return out;
  }
  return value;
}

function hex(buf) {
  return Buffer.from(buf).toString("hex");
}

/** Reader over a Buffer; drip mode returns at most one byte per recv(). */
function makeReader(data, drip) {
  let offset = 0;
  return {
    recv(size) {
      if (offset >= data.length) return Buffer.alloc(0);
      const take = drip ? Math.min(1, size) : size;
      const chunk = data.subarray(offset, offset + take);
      offset += chunk.length;
      return chunk;
    },
  };
}

/** Run encode_server_packet capturing console.log (Python print parity). */
function captureEncode(codec, opcode, payloadHex) {
  const captured = [];
  const orig = console.log;
  console.log = function () {
    captured.push(Array.from(arguments).join(" "));
  };
  try {
    const wire = codec.encode_server_packet(opcode, Buffer.from(payloadHex, "hex"));
    return { wire, captured };
  } finally {
    console.log = orig;
  }
}

// --- static tables -------------------------------------------------------------

check("tables match Python CLIENT_PACKET_LENGTHS", () => {
  assert.deepStrictEqual(
    { ...packets.CLIENT_PACKET_LENGTHS },
    fixture.tables.client_packet_lengths
  );
});
check("tables match Python SERVER_PACKET_LENGTHS", () => {
  assert.deepStrictEqual(
    { ...packets.SERVER_PACKET_LENGTHS },
    fixture.tables.server_packet_lengths
  );
});
check("tables match Python LOBBY_ACTION_NAMES", () => {
  assert.deepStrictEqual(
    { ...packets.LOBBY_ACTION_NAMES },
    fixture.tables.lobby_action_names
  );
});
check("tables match Python SERVER_OPCODES_SEEN_ENABLED", () => {
  assert.deepStrictEqual(
    [...packets.SERVER_OPCODES_SEEN_ENABLED].sort((a, b) => a - b),
    fixture.tables.server_opcodes_seen_enabled
  );
});
vectors += 4;

// --- PacketBuilder ---------------------------------------------------------------

const NUMERIC_OPS = new Set(["u8", "i8", "u16", "u24", "u32", "u64", "varint7"]);

for (const c of fixture.builder) {
  check("builder " + c.name, () => {
    if (c.error !== undefined) {
      assert.throws(() => {
        const pb = new packets.PacketBuilder();
        for (const op of c.ops) {
          const [method] = op;
          const args = op.slice(1);
          if (method === "raw") pb.raw(Buffer.from(args[0], "hex"));
          else if (method === "u64" && typeof args[0] === "string") pb.u64(args[0]);
          else if (NUMERIC_OPS.has(method)) pb[method](Number(args[0]));
          else pb[method].apply(pb, args);
        }
        pb.finish();
      }, (err) => err.name === c.error_type && err.message === c.error);
      return;
    }
    const pb = new packets.PacketBuilder();
    for (const op of c.ops) {
      const [method] = op;
      const args = op.slice(1);
      if (method === "raw") pb.raw(Buffer.from(args[0], "hex"));
      else if (method === "u64" && typeof args[0] === "string") pb.u64(args[0]);
      else if (NUMERIC_OPS.has(method)) pb[method](Number(args[0]));
      else pb[method].apply(pb, args);
    }
    assert.strictEqual(hex(pb.finish()), c.out_hex, "builder bytes diverged");
  });
  vectors += 1;
}

// --- pack_5bit ----------------------------------------------------------------------

for (const c of fixture.pack_5bit) {
  check("pack_5bit " + c.name, () => {
    assert.strictEqual(hex(packets.pack_5bit(c.values)), c.out_hex);
  });
  vectors += 1;
}
check("pack_5bit accepts typed arrays too", () => {
  const c = fixture.pack_5bit.find((x) => x.name === "eight_mixed");
  assert.strictEqual(
    hex(packets.pack_5bit(Int32Array.from(c.values))),
    c.out_hex
  );
});
vectors += 1;

// --- unpack_5bit ----------------------------------------------------------------------

for (const c of fixture.unpack_5bit) {
  check("unpack_5bit " + c.name, () => {
    const data = Buffer.from(c.data_hex, "hex");
    if (c.error !== undefined) {
      assert.throws(() => packets.unpack_5bit(data, c.count), (err) =>
        err.name === c.error_type && err.message === c.error
      );
      return;
    }
    assert.deepStrictEqual(packets.unpack_5bit(data, c.count), c.out);
  });
  vectors += 1;
}

// --- decode_control_batch ---------------------------------------------------------------

for (const c of fixture.decode_control_batch) {
  check("decode_control_batch " + c.name, () => {
    const payload = Buffer.from(c.payload_hex, "hex");
    if (c.error !== undefined) {
      assert.throws(() => packets.decode_control_batch(payload), (err) =>
        err.name === c.error_type && err.message === c.error
      );
      return;
    }
    assert.deepStrictEqual(packets.decode_control_batch(payload), c.out);
  });
  vectors += 1;
}

// --- PacketCodec.encode_server_packet -----------------------------------------------------

// Python generated each label's cases with ONE reused codec (the outbound
// ISAAC stream advances case to case), so replay them in the same order.
const encodeCodecs = {};
function codecFor(label) {
  if (encodeCodecs[label] === undefined) {
    encodeCodecs[label] = new packets.PacketCodec(
      fixture.codec_decode.find((s) => s.label === label).seed
    );
  }
  return encodeCodecs[label];
}

for (const c of fixture.codec_encode.cases) {
  const seedLabel = c.label;
  check("codec_encode " + seedLabel + " op " + c.opcode, () => {
    const codec = codecFor(seedLabel);
    const { wire, captured } = captureEncode(codec, c.opcode, c.payload_hex);
    assert.strictEqual(hex(wire), c.wire_hex, "wire bytes diverged");
    if (c.warning !== undefined) {
      assert.strictEqual(captured.length, 1, "expected exactly one warning");
      assert.strictEqual(captured[0], c.warning, "warning text diverged");
    } else {
      assert.strictEqual(captured.length, 0, "unexpected warning printed");
    }
  });
  vectors += 1;
}

for (const e of fixture.codec_encode.errors) {
  check("codec_encode error " + e.label + "/" + e.case, () => {
    const codec = new packets.PacketCodec(fixture.codec_decode.find(
      (s) => s.label === e.label
    ).seed);
    let threw = null;
    try {
      if (e.case === "fixed_mismatch") captureEncode(codec, 0, "01");
      else if (e.case === "too_long_u8") captureEncode(codec, 9, "00".repeat(256));
      else if (e.case === "too_long_u16") captureEncode(codec, 2, "00".repeat(65536));
    } catch (err) {
      threw = err;
    }
    assert.notStrictEqual(threw, null, "expected a throw");
    assert.strictEqual(threw.name, e.error_type, "error class name");
    assert.strictEqual(threw.message, e.error, "error message");

    if (e.case === "fixed_mismatch") {
      // The failed encode must already have burned one outbound ISAAC word.
      const after = captureEncode(codec, 0, "");
      assert.strictEqual(hex(after.wire), e.post_error_wire_hex,
        "post-error keystream position diverged");
      assert.strictEqual(after.captured.length, 0);
    }
  });
  vectors += 1;
}

// --- PacketCodec.read_client_packet ---------------------------------------------------------

for (const s of fixture.codec_decode) {
  for (const drip of [false, true]) {
    check(
      "codec_decode " + s.label + (drip ? " byte-drip" : ""),
      () => {
        const data = Buffer.from(s.stream_hex, "hex");
        const codec = new packets.PacketCodec(s.seed);
        const reader = makeReader(data, drip);
        for (const want of s.frames) {
          const gp = codec.read_client_packet(reader);
          assert.strictEqual(gp.opcode, want.opcode, "opcode for " + want.kind);
          assert.strictEqual(
            hex(gp.payload),
            want.payload_hex,
            "payload for " + want.kind
          );
          assert.strictEqual(
            gp.assumed_variable,
            want.assumed_variable,
            "assumed_variable for " + want.kind
          );
        }
        // The stream must be consumed exactly.
        assert.strictEqual(reader.recv(1).length, 0, "trailing bytes left");
      }
    );
    vectors += s.frames.length;
  }
}

// --- make_server_message -----------------------------------------------------------------------

// Python's make_server_message section used a FRESH codec per label (the
// encode section above must not share its keystream position).
const messageCodecs = {};
for (const c of fixture.server_message) {
  check("server_message " + c.label + "/" + c.text_name, () => {
    if (messageCodecs[c.label] === undefined) {
      messageCodecs[c.label] = new packets.PacketCodec(
        fixture.codec_decode.find((s) => s.label === c.label).seed
      );
    }
    assert.strictEqual(
      hex(messageCodecs[c.label].make_server_message(c.text)),
      c.wire_hex
    );
  });
  vectors += 1;
}

// --- build_* families ------------------------------------------------------------------------------

const BUILDERS = {
  build_sb_reply: packets.build_sb_reply,
  build_achievements_reply: packets.build_achievements_reply,
  build_achievement_mask: packets.build_achievement_mask,
  build_f_reply: packets.build_f_reply,
  build_chat_broadcast: packets.build_chat_broadcast,
  build_quickchat_broadcast: packets.build_quickchat_broadcast,
  build_room_membership: packets.build_room_membership,
  build_achievement_ack: packets.build_achievement_ack,
  build_hiscore_table: packets.build_hiscore_table,
  build_ignore_entry: packets.build_ignore_entry,
  build_friend_entry: packets.build_friend_entry,
  build_player_joined_room: packets.build_player_joined_room,
  build_player_left_room: packets.build_player_left_room,
  build_leave_room_reply: packets.build_leave_room_reply,
  build_kicked_room_reply: packets.build_kicked_room_reply,
  build_add_room: packets.build_add_room,
  build_remove_room: packets.build_remove_room,
  build_room_invitation: packets.build_room_invitation,
  build_lobby_player_left: packets.build_lobby_player_left,
  build_host_invitation_added: packets.build_host_invitation_added,
  build_host_invitation_removed: packets.build_host_invitation_removed,
  build_create_room_reply: packets.build_create_room_reply,
  build_local_player_id: packets.build_local_player_id,
  build_lobby_player: packets.build_lobby_player,
  build_social_list_complete: packets.build_social_list_complete,
};

for (const c of fixture.builds) {
  const label = c.family + "/" + c.name;
  check(label, () => {
    const fn = BUILDERS[c.family];
    assert.strictEqual(typeof fn, "function", "missing export " + c.family);
    const args = conv(c.args);
    const kwargs = conv(c.kwargs);
    if (c.error !== undefined) {
      assert.throws(() => fn.apply(null, args.concat([kwargs])), (err) =>
        err.name === c.error_type && err.message === c.error
      );
      return;
    }
    const out = fn.apply(null, args.concat([kwargs]));
    assert.strictEqual(hex(out), c.out_hex, label + " bytes diverged");
  });
  vectors += 1;
}

// --- port-level properties beyond the fixture --------------------------------------------------------

check("GamePacket is frozen with dataclass defaults", () => {
  const gp = new packets.GamePacket(7, Buffer.from([1, 2]), true);
  assert.strictEqual(gp.opcode, 7);
  assert.deepStrictEqual([...gp.payload], [1, 2]);
  assert.strictEqual(gp.assumed_variable, true);
  assert.throws(() => {
    "use strict";
    gp.opcode = 9;
  }, TypeError);

  const plain = new packets.GamePacket(8, Buffer.alloc(0));
  assert.strictEqual(plain.assumed_variable, false, "dataclass default false");
});

check("cp1252 specials encode like Python", () => {
  const text = "\u00e9\u00f1\u00df\u00d7\u20ac\u2014\u2018a\u2019";
  assert.strictEqual(hex(packets.encode_cp1252(text)), "e9f1dfd78097916192");
  // C1 controls and unmappable code points become '?', matching errors="replace".
  assert.strictEqual(hex(packets.encode_cp1252("\u0081\u2603")), "3f3f");
});

check("server-to-client round-trip through mirrored ISAAC", () => {
  const { IsaacCipher } = require("../src/crypto.js");
  const seed = [11, 22, 33, 44];
  const server = new packets.PacketCodec(seed);
  // The peer decodes server packets with an inbound cipher seeded exactly
  // like the server's outbound: u32(value + 50).
  const peer = Object.create(packets.PacketCodec.prototype);
  peer.inbound = new IsaacCipher(seed.map((v) => v + 50));

  // Opcodes 4, 11, 12 carry identical (-1) framing in BOTH direction tables,
  // so server-encoded frames are valid client-framed reads. Payloads come
  // from three different builders to keep the mix honest.
  const wire = Buffer.concat([
    server.encode_server_packet(4, packets.build_sb_reply(3)),
    server.encode_server_packet(12, packets.build_quickchat_broadcast("Pat", 42)),
    server.encode_server_packet(
      11,
      packets.build_chat_broadcast("Zed", 5, Buffer.from("hello"), 0)
    ),
  ]);
  const reader = makeReader(wire, false);
  const got = [
    peer.read_client_packet(reader),
    peer.read_client_packet(reader),
    peer.read_client_packet(reader),
  ];
  assert.deepStrictEqual(got.map((g) => g.opcode), [4, 12, 11]);
  assert.strictEqual(hex(got[0].payload), "000003000000");
  // quickchat payload: flags=00, tg.field_c=01, u64 0, var4=00, "Pat"+NUL, id=42
  assert.strictEqual(
    hex(got[1].payload),
    "0001" + "0000000000000000" + "00" + "506174" + "00" + "002a"
  );
  assert.ok(got.every((g) => g.assumed_variable === false));
  assert.strictEqual(reader.recv(1).length, 0, "stream fully consumed");
});

check("decode_control_batch rejects non-empty count>20 before unpacking", () => {
  // 21 values would need ceil(21*5/8)=14 bytes; the guard fires first either way.
  assert.throws(
    () => packets.decode_control_batch(Buffer.from([21])),
    (err) =>
      err.name === "ValueError" &&
      err.message === "control batch count exceeds client buffer: 21"
  );
});

check("build_sb_reply mirrors int.to_bytes overflow", () => {
  assert.throws(() => packets.build_sb_reply(-1), (err) =>
    err.name === "OverflowError" &&
    err.message === "can't convert negative int to unsigned"
  );
  assert.throws(() => packets.build_sb_reply(2 ** 32), (err) =>
    err.name === "OverflowError" && err.message === "int too big to convert"
  );
});

// ------------------------------------------------------------------------------

console.log(
  "packets: " +
    pass +
    "/" +
    (pass + failures.length) +
    " checks passed (" +
    vectors +
    " fixture vectors)"
);
for (const f of failures) console.log("  FAIL " + f);
process.exit(failures.length === 0 ? 0 : 1);
