'use strict';

// Golden-vector tests for src/io.js against fixtures/io.json
// (generated by RUNNING apps/server/dekobloko_server/io.py).

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const io = require('../src/io.js');

const fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'io.json'), 'utf8')
);

class FakeSock {
  constructor(hex) {
    this._buf = Buffer.from(hex, 'hex');
    this.sent = Buffer.alloc(0);
  }
  recv(size) {
    if (this._buf.length === 0) return Buffer.alloc(0);
    const chunk = Buffer.from(this._buf.subarray(0, size));
    this._buf = this._buf.subarray(chunk.length);
    return chunk;
  }
  sendAll(buf) {
    this.sent = Buffer.concat([this.sent, buf]);
  }
}

let pass = 0;
const failures = [];

function check(label, fn) {
  try {
    fn();
    pass += 1;
  } catch (err) {
    failures.push(label + ': ' + err.message);
  }
}

for (const c of fixture.cases) {
  const label = c.op + '(' + (c.in_hex !== undefined ? c.in_hex : c.value) + ')';
  check(label, () => {
    switch (c.op) {
      case 'read_exact': {
        const sock = new FakeSock(c.in_hex);
        assert.strictEqual(io.read_exact(sock, c.size).toString('hex'), c.out_hex);
        break;
      }
      case 'read_exact_eof': {
        const sock = new FakeSock(c.in_hex);
        assert.throws(
          () => io.read_exact(sock, c.size),
          (err) => err.name === c.error && err.message === c.message
        );
        break;
      }
      case 'read_u8': {
        const out = io.read_u8(new FakeSock(c.in_hex));
        assert.strictEqual(out, c.out, 'read_u8 got ' + out);
        break;
      }
      case 'read_u16': {
        const out = io.read_u16(new FakeSock(c.in_hex));
        assert.strictEqual(out, c.out, 'read_u16 got ' + out);
        break;
      }
      case 'read_i32': {
        const out = io.read_i32(new FakeSock(c.in_hex));
        assert.strictEqual(out, c.out, 'read_i32 got ' + out);
        break;
      }
      case 'write_u8': {
        const sock = new FakeSock('');
        io.write_u8(sock, c.value);
        assert.strictEqual(sock.sent.toString('hex'), c.out_hex);
        break;
      }
      case 'write_u16': {
        const sock = new FakeSock('');
        io.write_u16(sock, c.value);
        assert.strictEqual(sock.sent.toString('hex'), c.out_hex);
        break;
      }
      case 'write_u64': {
        const sock = new FakeSock('');
        io.write_u64(sock, BigInt(c.value));
        assert.strictEqual(sock.sent.toString('hex'), c.out_hex);
        break;
      }
      case 'hex_preview': {
        const out = io.hex_preview(Buffer.from(c.in_hex, 'hex'), c.limit);
        assert.strictEqual(out, c.out, 'hex_preview got ' + JSON.stringify(out));
        break;
      }
      default:
        throw new Error('unknown op in fixture: ' + c.op);
    }
  });
}

console.log('io: ' + pass + ' passed, ' + failures.length + ' failed');
for (const f of failures) console.log('  FAIL ' + f);
process.exit(failures.length === 0 ? 0 : 1);
